"""Remove residual trash generated by `sphinx`."""
from glob import glob
from os import remove


def remove_trash() -> None:
    """Remove residual trash generated by `sphinx`."""
    for file in glob("modules/mc_plugin_helper*.rst"):
        remove(file)


if __name__ == "__main__":
    remove_trash()
