name: Deploy to pypi.org

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python

          # Adding `poetry` to `$PATH`:
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: poetry install --only main

      - name: Build and push
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
